apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: zookeeper
  namespace: arkon-zookeeper
spec:
  releaseName: zookeeper
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: zookeeper
    version: 6.6.0
  values:
    replicaCount: 3
    persistence:
      enable: true
      accessModes:
        - ReadWriteOnce
      size: 10Gi
